name: Build Node | 构建Node

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch: # click the button on Github repo!

jobs:
  build-and-deploy:
    name: Automatic deployment | 自动部署
    runs-on: ubuntu-latest
    if: github.repository == 'misitebao/yakia'

    steps:
      - name: Checkout | 切换到部署分支
        uses: actions/checkout@v2
        with:
          ref: "main"
          submodules: true
          fetch-depth: 0

      - name: Build Site | 构建网站
        run: |
          node -v
